[package]
name = "yt-subscriber-rs"
version = "0.1.0"
authors = ["rschwalk <rschwalk@outlook.com>"]
edition = "2018"

[dependencies]
gio = "^0.6.0"
[dependencies.gtk]
version = "^0.6.0"
features = ["v3_20"]
